USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE SCD1_DB;
USE DATABASE SCD1_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE SCD1_DB.PUBLIC.CUSTOMER_SOURCE
(
    CUSTOMERNAME STRING,
    PHONE STRING,
    ADDRESSLINE1 STRING,
    ADDRESSLINE2 STRING,
    CITY STRING,
    STATE STRING,
    POSTALCODE STRING,
    COUNTRY STRING,
    TERRITORY STRING,
    CONTACTFIRSTNAME STRING,
    CONTACTLASTNAME STRING
);

CREATE OR REPLACE TABLE SCD1_DB.PUBLIC.CUSTOMER
(
    CONTACTFIRSTNAME STRING,
    CONTACTLASTNAME STRING,
    CUSTOMERNAME STRING,
    PHONE STRING,
    ADDRESSLINE1 STRING,
    ADDRESSLINE2 STRING,
    CITY STRING,
    STATE STRING,
    POSTALCODE STRING,
    COUNTRY STRING,
    TERRITORY STRING,
    INSERT_DTS TIMESTAMP(6),
    UPDATE_DTS TIMESTAMP(6)
);
