USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SCD1_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE STORAGE INTEGRATION SCD1_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<aws-account-id>:role/scd1-snowflake-s3-role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://scd1-customer-data-jenny/data/');

DESC INTEGRATION SCD1_INT;

CREATE OR REPLACE STAGE SCD1_DB.PUBLIC.SCD1_STAGE
  STORAGE_INTEGRATION = SCD1_INT
  URL = 's3://scd1-customer-data-jenny/data/';

LS @SCD1_DB.PUBLIC.SCD1_STAGE;
