USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SCD1_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE PIPE SCD1_DB.PUBLIC.SCD1PIPE
AUTO_INGEST = TRUE AS
COPY INTO SCD1_DB.PUBLIC.CUSTOMER_SOURCE
FROM
(
    SELECT
        $1 AS CUSTOMERNAME,
        $2 AS PHONE,
        $3 AS ADDRESSLINE1,
        $4 AS ADDRESSLINE2,
        $5 AS CITY,
        $6 AS STATE,
        $7 AS POSTALCODE,
        $8 AS COUNTRY,
        $9 AS TERRITORY,
        $10 AS CONTACTFIRSTNAME,
        $11 AS CONTACTLASTNAME
    FROM @SCD1_DB.PUBLIC.SCD1_STAGE
)
FILE_FORMAT = (
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);

SELECT SYSTEM$PIPE_STATUS('SCD1_DB.PUBLIC.SCD1PIPE');

SHOW PIPES;
