USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SCD1_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE STREAM SCD1_DB.PUBLIC.CUSTOMER_STREAM
ON TABLE SCD1_DB.PUBLIC.CUSTOMER_SOURCE
APPEND_ONLY = TRUE;

SHOW STREAMS IN SCHEMA SCD1_DB.PUBLIC;

SELECT *
FROM SCD1_DB.PUBLIC.CUSTOMER_STREAM;
