USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SCD1_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TASK SCD1_DB.PUBLIC.CUSTOMER_TASK
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('SCD1_DB.PUBLIC.CUSTOMER_STREAM')
AS
    CALL SCD1_DB.PUBLIC.CUSTOMER_SP();

ALTER TASK SCD1_DB.PUBLIC.CUSTOMER_TASK RESUME;

SHOW TASKS LIKE 'CUSTOMER_TASK' IN SCHEMA SCD1_DB.PUBLIC;
