USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SCD1_DB;
USE SCHEMA PUBLIC;

-- Validate full load count.
SELECT COUNT(*) AS CUSTOMER_COUNT
FROM SCD1_DB.PUBLIC.CUSTOMER;

-- Before change checks.
SELECT *
FROM SCD1_DB.PUBLIC.CUSTOMER
WHERE CONTACTFIRSTNAME = 'Elizabeth'
  AND CONTACTLASTNAME = 'Yu';

SELECT *
FROM SCD1_DB.PUBLIC.CUSTOMER
WHERE CONTACTFIRSTNAME = 'Kyung'
  AND CONTACTLASTNAME = 'Benitez';

SELECT *
FROM SCD1_DB.PUBLIC.CUSTOMER
WHERE CONTACTFIRSTNAME = 'John'
  AND CONTACTLASTNAME = 'Wick';

-- After change load, expected final count is 81.
SELECT COUNT(*) AS CUSTOMER_COUNT
FROM SCD1_DB.PUBLIC.CUSTOMER;

-- After change checks.
SELECT *
FROM SCD1_DB.PUBLIC.CUSTOMER
WHERE CONTACTFIRSTNAME = 'Elizabeth'
  AND CONTACTLASTNAME = 'Yu';

SELECT *
FROM SCD1_DB.PUBLIC.CUSTOMER
WHERE CONTACTFIRSTNAME = 'Kyung'
  AND CONTACTLASTNAME = 'Benitez';

SELECT *
FROM SCD1_DB.PUBLIC.CUSTOMER
WHERE CONTACTFIRSTNAME = 'John'
  AND CONTACTLASTNAME = 'Wick';
